// Repository-specific inputs to the release scripts. The other scripts/*.mjs
// are verbatim copies of scshafe-dev's master (release/scripts/); change this
// file, not them. Generated by scshafe-dev v0.1.0.
export default {
  // Each directory in package.json `files` and what it may contain. graphpaper
  // ships src/ as written (plain JavaScript; the types are the hand-written
  // index.d.ts at the root), so src/ holds .js only.
  payload: { src: "\\.js$" },
  // Build output `pnpm run clean` removes; never committed (LIB-03).
  // graphpaper has no build step and no build output.
  clean: [],
  // Packages the smokes need beside the peers (exact devDependencies).
  smokeExtraPackages: [],
  // Optional-peer phases, e.g. [{ name: "editor", peers: ["@tiptap/core"] }]:
  // the base smokes prove these peers are absent, then each phase adds its
  // peers and runs test/smoke/<name>/. elkjs is an optional peer: the base
  // smokes run the built-in layered fallback with no ELK installed, then the
  // elk phase adds elkjs and lays out with an injected `new ELK()`.
  phases: [{ name: "elk", peers: ["elkjs"] }],
  // false: the TypeScript smoke also checks the peers' declarations.
  typeSmokeSkipLibCheck: false,
  // DOM as well: peers' declarations name AbortSignal and friends (the
  // switchyard-postgres and graphpaper smokes check them the same way).
  typeSmokeLib: ["ES2022", "DOM"]
};
